name: Overlay

on:
  pull_request:
    branches: [pie]

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt -y install git-core git xmlstarlet
        sudo apt update

    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var

    - name: Clone vendor_hardware_overlay
      run: |
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        git clone https://github.com/phhusson/vendor_hardware_overlay

    - name: Run test scripts
      run: |
        PATH=~/bin:$PATH
        cd workspace && cd vendor_hardware_overlay
        git config --global user.name "Johx22"
        git config --global user.email "johannjose2004@gmail.com"
        cd tests
        bash tests.sh

    - name: Build APK's
      run: |
        PATH=~/bin:$PATH
        cd workspace && cd vendor_hardware_overlay && cd build
        bash build.sh

    - name: Upload APK
      uses: actions/upload-artifact@v3.0.0
      with:
        path: workspace/vendor_hardware_overlay/build/*.apk
        name: OverlayZip
